<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title" style="float: left;"><b>Thêm mới bài viết</b></h4>
          <a href="<?= $this->url->get('backend/blogs') ?>" class="btn btn-success btn-fw mdi mdi-view-list" style="float: right; color: white"> Danh sách</a><br>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
              
            </p>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Tiêu đề</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="title" value="" />
                  </div>
                </div>
              </div>
            </div>
            <!-- row images -->
            <div class="row">
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-sm-2 col-form-label">Nội dung</label>
                  <div class="col-sm-10">
                    <textarea name="content" id="" cols="80" rows="20" style="font-size: 15px"></textarea>
                  </div>
                </div>
              </div>
            </div>
            <button class="btn btn-primary" style="color: white">Thêm mới</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- content-wrapper ends -->