<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
    	<?php $this->flashSession->output() ?>
      <h4 class="card-title">Quản lý khách hàng</h4>
      <!-- <a class="btn btn-success btn-fw mdi mdi-database-plus" style="float: right; color: white"> Tạo</a><br> -->
      <p class="card-description"><hr></p>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <th>Họ Tên</th>
              <th>Đăng nhập</th>
              <th>Điện thoại</th>
              <th>Email</th>
              <th>Địa chỉ</th>
              <th>Source</th>
              <th>Ngày tạo</th>
              <th>Ngày update</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          	<?php $count = 1; foreach ($users as $user): ?>
            <tr>
              <td><?= $count ?></td>
              <td><?= $user->display_name ?></td>
              <td><?= $user->name ?></td>
              <td><?= $user->phone ?></td>
              <td><?= $user->email ?></td>
              <td><?= $user->address ?></td>
              <td><?= $user->source ?></td>
              <td><?= Date("d/m/Y", $user->created_at) ?></td>
              <td><?= Date("d/m/Y", $user->updated_at) ?></td>
              <td style="font-size: 20px">
              	<a href="<?= $this->url->get('backend/users/update/'.$user->_id->{'$id'}) ?>" class="mdi mdi-pencil" title="Update"></a>
              	<a href="<?= $this->url->get('backend/users/delete/'.$user->_id) ?>" class="mdi mdi-delete" title="Delete" onclick="return confirm('Bạn có chắc muốn xóa?')"></a>
              </td>
            </tr>
        	<?php $count += 1; endforeach;?>
          </tbody>
        </table>
    </div>
    </div>
  </div>
</div>