<div class="container">
	<div class="box-icon row">
		<div class="col-md-4 col-sm-4 col-xs-12">
			<div class="banner-footer-item">
				<img src="<?php echo $this->url->get('img/14/icon-vanchuyen87e5.png') ?>">
				<div class="banner-footer-item-info">
					<p class="banner-footer-item-title">Miễn phí vận chuyển toàn quốc</p>
					<p class="banner-footer-item-des">Với Đơn Hàng Trên 500.000 đ</p>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12">
			<div class="banner-footer-item">
				<img src="<?php echo $this->url->get('img/14/icon-hotro87e5.png') ?>">
				<div class="banner-footer-item-info">
					<p class="banner-footer-item-title">Hỗ trợ 24/7</p>
					<p class="banner-footer-item-des"><?= $setting->phone_support ?></p>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12">
			<div class="banner-footer-item">
				<img src="<?php echo $this->url->get('img/14/icon-doitra87e5.png') ?>">
				<div class="banner-footer-item-info">
					<p class="banner-footer-item-title">Miễn phí đổi trả</p>
					<p class="banner-footer-item-des">Trong Vòng 10 ngày</p>
				</div>
			</div>
		</div>
	</div>
</div>