<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
    	<?php $this->flashSession->output() ?>
      <h4 class="card-title" style="float: left;">Quản lý danh mục sản phẩm</h4>
      <a href="<?= $this->url->get('backend/categories/add') ?>" class="btn btn-success btn-fw mdi mdi-database-plus" style="float: right; color: white"> Tạo mới</a><br>
      <p class="card-description"><hr></p>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <th>Tên danh mục</th>
              <th>Danh mục cha</th>
              <th>Hình ảnh</th>
              <th>Ngày tạo</th>
              <th>Ngày update</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          	<?php $count = 1; foreach ($categories as $category): ?>
            <tr>
              <td><?= $count ?></td>
              <td><?= $category->title ?></td>
              <td><?= $category->parent_id ?></td>
              <td><img src="<?= $this->url->get('img/collection/'.$category->images['image']) ?>" alt=""></td>
              <td><?= Date("d/m/Y", $category->created_at) ?></td>
              <td><?= Date("d/m/Y", $category->updated_at) ?></td>
              <td style="font-size: 20px">
              	<a href="<?= $this->url->get('backend/categories/update/'.$category->_id) ?>" class="mdi mdi-pencil" title="Update"></a>
              	<a href="<?= $this->url->get('backend/categories/delete/'.$category->_id) ?>" class="mdi mdi-delete" title="Delete" onclick="return confirm('Bạn có chắc muốn xóa?')"></a>
              </td>
            </tr>
        	<?php $count += 1; endforeach;?>
          </tbody>
        </table>
    </div>
    </div>
  </div>
</div>