<div class="row clearfix collection-top">
	<div class="collection-left">
		<h1>Sản Phẩm Bán Chạy</h1>
		<div class="description">
			<img src="<?= $this->url->get('img/collection/sh_web_contact_cuahang-04.png') ?>" alt="Sản Phẩm Bán Chạy" />
		</div>
	</div>
	<div class="collection-img hidden-xs">
		<div class="img" style="background: url(<?= $this->url->get('img/file/banner_website-02.png') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
	</div>
</div><hr>