</script>
<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title" style="float: left;"><b>Sản phẩm <?= $product->title ?></b></h4>
          <br>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
              Thông tin sản phẩm
            </p>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Tên sản phẩm</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="title" value="<?= $product->title ?>" />
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Danh mục</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="title" value="<?= $product->category ?>" />
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Giá nhập</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="in_price" value="<?= $product->price['in_price'] ?>" />
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Giá bán</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="sale_price" value="<?= $product->price['sale_price'] ?>" />
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Giá khuyến mãi</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="promo_price" value="<?= $product->price['promo_price'] ?>" />
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Số lượng</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" disabled name="total" value="<?= $product->total ?>" />
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <!-- row images -->
            <div class="row" id="boximages">
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-sm-2 col-form-label">Hình ảnh</label>
                  <!-- print images -->
                  <?php $images = $product->images ?>
                  <?php foreach ($images as $image) : ?>
                  <div class="col-sm-2">
                    <img src="<?= $this->url->get('img/product/'.$image['link']) ?>" alt="" style="width: 70px; margin-bottom: 10px">
                    <!-- <div onclick="delImage()" class="btn btn-icons btn-rounded btn-outline-secondary" id="<?= $link ?>"><i class="mdi mdi-delete"></i></div> -->
                  </div>
                  <?php endforeach; ?>
                </div>
              </div>
            </div> 
            <hr>
            <!-- row checkbox size -->
            <div class="row">
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-sm-2 col-form-label">Size</label>
                  <?php $sizes = $product->details['size'];
                    foreach ($sizes as $size) : ?>
                      <div class="col-sm-1">
                        <?= $size ?>
                      </div>
                    <?php endforeach; ?>
                </div>
              </div>
            </div>
            <hr>   
            <div class="row">
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-sm-2 col-form-label">Mô tả</label>
                  <div class="col-sm-9">
                    <textarea class="form-control" rows="7" disabled name="description"><?= $product->details['description'] ?></textarea>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>