<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <div class="row bs-wizard">
       <!-- complete active disabled-->
        <?php switch ($orders->status) {
          case 'Mới':
            echo '<div class="col-xs-3 bs-wizard-step active"> 
                    <div class="text-center bs-wizard-stepnum">Mới</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Xác nhận</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Đang giao</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Hoàn thành</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>';
            break;
          case 'Đã xác nhận':
            echo '<div class="col-xs-3 bs-wizard-step complete"> 
                    <div class="text-center bs-wizard-stepnum">Mới</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step active">
                    <div class="text-center bs-wizard-stepnum">Xác nhận</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Đang giao</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Hoàn thành</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>';
            break;
          case 'Đang giao':
            echo '<div class="col-xs-3 bs-wizard-step complete"> 
                    <div class="text-center bs-wizard-stepnum">Mới</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step complete">
                    <div class="text-center bs-wizard-stepnum">Xác nhận</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step active">
                    <div class="text-center bs-wizard-stepnum">Đang giao</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step disabled">
                    <div class="text-center bs-wizard-stepnum">Hoàn thành</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>';
            break;
          case 'Hoàn thành':
            echo '<div class="col-xs-3 bs-wizard-step complete"> 
                    <div class="text-center bs-wizard-stepnum">Mới</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step complete">
                    <div class="text-center bs-wizard-stepnum">Xác nhận</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step complete">
                    <div class="text-center bs-wizard-stepnum">Đang giao</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>
                  <div class="col-xs-3 bs-wizard-step complete">
                    <div class="text-center bs-wizard-stepnum">Hoàn thành</div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <div class="bs-wizard-dot"></div>
                  </div>';
            break;
          default:
            break;
        } ?>
      </div><br>
      <h4 class="card-title" style="float: left;"><b>Chi tiết đơn hàng</b></h4>
      <a href="<?= $this->url->get('backend/orders') ?>" class="btn btn-primary btn-fw mdi mdi-view-list" style="float: right; color: white"> Danh sách</a><br>
      <p class="card-description"><hr></p>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <th>Tên sản phẩm</th>
              <th>Giá bán</th>
              <th>Số lượng</th>
              <th>Kích cỡ</th>
              <th>Tổng tiền</th>
            </tr>
          </thead>
          <tbody>
            <?php $count = 1; foreach ($orders->product as $product): ?>
            <tr>
              <td><?= $count ?></td>
              <td><a href="<?= $this->url->get('backend/products/show/'.$product['id']) ?>">
                <?= $product['name'] ?></a></td>
              <td><?= number_format($product['price']) ?> <u>&#273</u></div></td>
              <td><?= $product['quantity'] ?></td>
              <td><?= $product['size'] ?></td>
              <td><?= number_format($product['total_price']) ?> <u>&#273</u></td>
            </tr>
          <?php $count += 1; endforeach;?>
          </tbody>
        </table><br>
        <div class="orders total_price" style="float: right; margin-right: 40px"><b>
          <span>Tổng trị giá đơn hàng: </span>
          <?= number_format($orders->total_price) ?> <u>&#273</u></b>
        </div><br><hr>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Tên khách hàng: </label>
              <div class="col-sm-8 col-form-label"><?= $orders->customer_name ?></div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Điện thoại: </label>
              <div class="col-sm-9 col-form-label"><?= $orders->customer_phone ?></div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Địa chỉ: </label>
              <div class="col-sm-10 col-form-label"><?= $orders->customer_address ?></div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group row">
              <label class="col-sm-3 col-form-label">Email: </label>
              <div class="col-sm-9 col-form-label"><?= $orders->customer_email ?></div>
            </div>
          </div>
        </div>
      </div><hr>
      <form action="" method="post">
        <?php switch ($orders->status) {
          case 'Mới':
            echo '<button type="submit" class="btn btn-danger btn-fw" name="progress" value="confirm">Xác nhận</button>';
            break;
          case 'Đã xác nhận':
            echo '<button type="submit" class="btn btn-info btn-fw" name="progress" value="deliver">Giao hàng</button>';
            break;
          case 'Đang giao':
            echo '<button type="submit" class="btn btn-success btn-fw" name="progress" value="completed">Hoàn thành</button>';
            break;
          case 'Hoàn thành':
            break;
          case 'Đã hủy':
            break;
        } ?>
      </form>
    </div>
  </div>
</div>