<?php ?>
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
      <div class="card-body">
      <?php $this->flashSession->output() ?>
      <h4 class="card-title" style="float: left;"><b>Báo cáo thống kê</b></h4><br>
      <p class="card-description"><hr>
        <form action="" method="get" id="ajaxform">
        <div class="col-md-12">
          <div class="form-group row">
            <label class="col-sm-1 col-form-label">Lọc:</label>
            <div class="col-sm-3">
              <select class="form-control" name="key_sort" id="key_sort">
                <option value="san-pham" <?= @$params['key_sort']=='san-pham'?'selected':'' ?>>
                Theo sản phẩm</option>
                <option value="loai-san-pham" <?= @$params['key_sort']=='loai-san-pham'?'selected':'' ?>>
                Theo loại sản phẩm</option>
              </select>
            </div>
            <label class="col-sm-1 col-form-label">Tháng:</label>
            <div class="col-sm-3">
              <select class="form-control" name="from_month" id="from_month">
                <?php for ($i=1; $i <=12 ; $i++) : ?>
                  <option value="<?= $i ?>" <?= @$params['from_month']== $i?'selected':'' ?>>
                  Tháng <?= $i ?></option>
                <?php endfor; ?>
              </select>
            </div>
            <label class="col-sm-1 col-form-label">Năm:</label>
            <div class="col-sm-3">
              <select class="form-control" name="from_year" id="from_year">
                <!-- <option value=""></option> -->
                <option value="2018">Năm 2018</option>
              </select>
            </div>
          </div>
        </div>
        </form>
      </p>
      <!-- check if report exists -->
      <?php if (isset($report)) : ?>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <?= @$params['key_sort']=='san-pham'?'<th>Sản phẩm</th>':'' ?>
              <?= @$params['key_sort']=='loai-san-pham'?'<th>Loại sản phẩm</th>':'' ?>
              <th>Số lượng</th>
              <th>Trị giá</th>
            </tr>
          </thead>
          <tbody>
              <?php $total_orders = 0; ?>
            	<?php $count=1; foreach ($report as $value) : ?>
                <tr>
                  <td><?= $count ?></td>
                  <td>
                    <?php switch (@$params['key_sort']) {
                      case 'loai-san-pham':
                        echo $value['name'];
                        break;
                      case 'san-pham':
                        echo Phalcon\Tag::linkTo('backend/products/show/'.$value['id'], $value['name']);
                        break;
                      default:
                        break;
                    } ?>
                  </td>
                  <td><?= $value['quantity'] ?></td>
                  <td><?= number_format($value['total_price']) ?> <u>đ</u></td>
                </tr>
                <?php $total_orders += $value['total_price'] ?>
            	<?php $count+=1; endforeach; ?>
              <tr>
                <td align="right" colspan="3">Tổng trị giá:</td>
                <td colspan="1"><?= number_format($total_orders) ?> <u>đ</u></td>
              </tr>
          </tbody>
        </table>
      </div>
      <?php endif; ?>
	  </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function () {
    $('#from_month').change(function () {
      $('#ajaxform').submit();
    });
    $('#key_sort').change(function () {
      $('#ajaxform').submit();
    });
    $('#from_year').change(function () {
      $('#ajaxform').submit();
    });
  });
</script>