<div id="layout-page" class="pd40">
	<div  class="container">
		<div class="main-title2 text-center mb30">
			<h1>Tài khoản của bạn <a class="logout" href="<?= $this->url->get('account/logout') ?>"><span class="fa fa-sign-out"></span>Thoát</a></h1>
		</div>
		<div class="content-page">
			<form accept-charset='UTF-8' action='' method='post'>
				<div class="col-md-6 col-md-offset-3">
					<div class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
						<input type="text" class="form-control textbox" name="display_name"  size="40" value="<?= $user->display_name ?>" placeholder="Tên">
					</div>
				</div>
				<div class="col-md-6 col-md-offset-3">
					<div class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
						<input type="text" class="form-control textbox" name="address"  size="40" value="<?= $user->address ?>" placeholder="Địa chỉ">
					</div>
				</div>
				<div class="col-md-6 col-md-offset-3">
					<div class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-phone-alt"></i></span>
						<input type="text" class="form-control textbox" name="phone"  size="40" value="<?= $user->phone ?>" placeholder="Số điện thoại">
					</div>
				</div>
				<div class="col-md-6 col-md-offset-3">
					<div class="action_bottom">
						<input class="btn bt-primary" type="submit" value="Cập nhật" />
						<span class="">hoặc <a href="<?= $this->url->get('account') ?>">Hủy</a></span>
					</div>  
				</div>
			</form>
		</div>
	</div>
</div>