<?php if (!$cart->getContent()) : ?>
<div id="cart">
	<div class="fix-breadcrumb " >
	<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
     <li><a href="<?= $this->url->get('') ?>" target="_self">Trang chủ</a></li>
     <li class="active"><span>Giỏ hàng </span>
     </li>
   </ol>
</div>
<div class="container">
	<!-- Begin empty cart -->
	<div class="row" >
		<div id="layout-page" class="col-md-12">
         <br>
         <?= $this->flashSession->output() ?>
			<div class="main-title2 mb30">
				<h1>Giỏ hàng</h1>
			</div>
			<p class="text-center">
				Không có sản phẩm nào trong giỏ hàng!</p>
			<p class="text-center"><a  href="<?= $this->url->get('collections') ?>">
				<i class="fa fa-reply"></i> Tiếp tục mua hàng</a>
			</p>
		</div>
	</div>
	<!-- End empty cart
   Begin cart -->
</div>
<?php else: ?>
<div id="cart">
   <div class="fix-breadcrumb " >
      <ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
        <li><a href="<?= $this->url->get('') ?>" target="_self">Trang chủ</a></li>
        <li class="active"><span>Giỏ hàng </span>
        </li>
      </ol>
   </div>
   <div class="container">
      <!-- Begin empty cart -->
      <div class="row" >
         <div id="layout-page" class="col-md-12">
            <br>
            <?= $this->flashSession->output() ?>
            <div class="main-title2 mb30">
               <h1>Giỏ hàng</h1>
            </div>
            <form action="" method="post" id="cartformpage" class="pb30">
               <table class="cart cart-hidden">
                  <thead>
                     <tr>
                        <th class="image">Hình ảnh</th>
                        <th class="item">Tên sản phẩm</th>
                        <th class="qty">Số lượng</th>
                        <th class="price">Giá tiền</th>
                        <th class="remove">Xoá</th>
                     </tr>
                  </thead>
                  <tbody>
                     <?php foreach ($cart->getContent() as $product) : ?>
                     <tr class="item">
                        <td class="image">
                           <div class="product_image">
                              <a href="<?= $this->url->get('products/'.$product['id']) ?>">
                              <img src="<?= $this->url->get('img/product/'.$product['img']) ?>" />
                              </a>
                           </div>
                        </td>
                        <td class="item">
                           <a href="<?= $this->url->get('products/'.$product['id']) ?>">
                           <strong><?= $product['name'] ?></strong>
                           </a>
                           <p class="variant_title"><?= $product['color'] ?> / <?= $product['size'] ?></p>
                        </td>
                        <td class="qty">
                           <input type="number" size="4" name="qty[]" min="1" max="20" id="updates_1030007666" value="<?= $product['qty'] ?>" class="tc item-quantity" />
                        </td>
                        <td class="price"><?= number_format($product['total']) ?>₫</td>
                        <td class="remove">
                           <a href="<?= $this->url->get('frontend/cart/del/'.$product['rowId']) ?>" class="cart"></a>
                        </td>
                     </tr>
                     <?php endforeach; ?>
                     <tr class="summary">
                        <td class="image">&nbsp;</td>
                        <td>&nbsp;</td>
                        <td style="font-size: 20px; text-transform: uppercase;">Tổng tiền</td>
                        <td class="price">
                           <span class="total" style="font-size: 25px;">
                           <strong><?= number_format($cart->getTotal()) ?>₫</strong>
                           </span>
                        </td>
                        <td>&nbsp;</td>
                     </tr>
                  </tbody>
               </table>
               <div class="cart-buttons inner-right inner-left">
                  <div class="buttons clearfix text-right">
                     <button type="submit" id="update-cart" class="button-default" name="update"  value="" >Cập nhật</button>
                     <button type="submit" id="checkout" class="button-default" name="checkout" value="" >Thanh toán</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<?php endif; ?>
<link rel="stylesheet" href="<?php echo $this->url->get('css/cart.css') ?>">
<script>
   $(document).ready(function () {
      $("[type='number']").keypress(function (evt) {
          evt.preventDefault();
      });
   });
</script>