<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <?php echo $this->flashSession->output() ?>
      <h4 class="card-title" style="float: left;">Quản trị Admin</h4>
      <a href="<?= $this->url->get('backend/admin/add') ?>" class="btn btn-success btn-fw mdi mdi-database-plus" style="float: right; color: white"> Tạo mới</a><br>
      <p class="card-description"><hr>
      </p>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>STT</th>
              <th>Họ Tên</th>
              <th>Điện thoại</th>
              <th>Email</th>
              <th>Địa chỉ</th>
              <th>Ngày tạo</th>
              <th>Ngày update</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          	<?php $count = 1; foreach ($admins as $admin): ?>
            <tr>
              <td><?= $count ?></td>
              <td><?= $admin->display_name ?></td>
              <td><?= $admin->phone ?></td>
              <td><?= $admin->email ?></td>
              <td><?= $admin->address ?></td>
              <td><?= Date("d/m/Y", $admin->created_at) ?></td>
              <td><?= Date("d/m/Y", $admin->updated_at) ?></td>
              <td style="font-size: 20px">
              	<a href="<?= $this->url->get('backend/admin/update/'.$admin->_id) ?>" class="mdi mdi-pencil" title="Update"></a>
              	<a href="<?= $this->url->get('backend/admin/delete/'.$admin->_id) ?>" class="mdi mdi-delete" title="Delete" onclick="return confirm('Bạn có chắc muốn xóa?')"></a>
              </td>
            </tr>
        	<?php endforeach; $count += 1;?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>