<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <?php $this->flashSession->output() ?>
          <h4 class="card-title""><b>Cài đặt thông tin chung</b></h4>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
             
            </p>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                   <label class="col-sm-3 col-form-label">Title</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="title" value="<?= $setting->title ?>" />
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Description</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="description" value="<?= $setting->description ?>" />
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Web thumbnail</label>
                  <div class="col-sm-6">
                    <input type="file" class="form-control" id="icon" name="web_thumbnail" placeholder="">
                  </div>
                  <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$setting->web_thumbnail) ?>" alt="" width="25px"></label>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Web logo</label>
                  <div class="col-sm-6">
                    <input type="file" class="form-control" id="icon" name="web_logo" placeholder="">
                  </div>
                  <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$setting->web_logo) ?>" alt="" width="30px"></label>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                  <div class="form-group row">
                  <label class="col-sm-2 col-form-label">Keywords</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="keywords" placeholder="" value="<?php echo $setting->keywords ?>">
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Facebook</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="facebook" placeholder="" value="<?php echo $setting->social['facebook'] ?>">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Instagram</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="instagram" placeholder="" value="<?php echo $setting->social['instagram'] ?>">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-4 col-form-label">Điện thoại hỗ trợ</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="phone_support" placeholder="" value="<?php echo $setting->phone_support ?>">
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <h4 class="card-title""><b>Cài đặt địa chỉ cửa hàng</b></h4>
            <p class="card-description">
             
            </p>
            <?php $count = 0; foreach ($setting->info as $info) : ?>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Địa chỉ <?= $count+1 ?>:</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="address[]" placeholder="" value="<?php echo $info['address'] ?>">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Điện thoại</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="phone[]" placeholder="" value="<?php echo $info['phone'] ?>">
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label"></label>
                  <div class="col-sm-9">
                    <input type="file" class="form-control" name="images<?= $count ?>" placeholder="">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                    <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$info['images']) ?>" alt="" height="40px"></label>
                      
                  </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                  <div class="form-group row">
                  <label class="col-sm-1 col-form-label">Maps:</label>
                  <div class="col-sm-8" style="margin-left: 40px">
                    <textarea class="form-control" rows="5" name="maps[]" width="100%"><?= $info['maps'] ?></textarea>
                  </div>
                  </div>
              </div>
            </div>
            <hr>
            <?php $count += 1; endforeach; ?>
            <button class="btn btn-primary" style="color: white">
              <i class="mdi mdi-settings"></i>Cập nhật thông tin</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>