<div id="layout-page" class="bgfafafa">
	<div class="container">
		<div id="customer-login">
			<div id="login" class="userbox">
				<h1>Đăng nhập</h1>
				<form accept-charset='UTF-8' action='' id='customer_login' method='post'>
					<input name='form_type' type='hidden' value='customer_login'>
					<input name='utf8' type='hidden' value='✓'>
					<?php if (isset($loginError)): ?>
						<div class="errors"><?= $loginError ?></div>
					<?php endif; ?>
					<input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>">
					<div class="clearfix large_form">
						<input required type="email" value="" name="email" id="customer_email" placeholder="Email" class="text" />
						<input required type="password" value="" name="password" id="customer_password" placeholder="Mật khẩu" class="text" />      
					</div>
					<div class="action_bottom text-center">
						<input class="btn-more btn-login" type="submit" value="Đăng nhập" />
						<a href="#" onclick="showRecoverPasswordForm();return false;">Quên mật khẩu?</a>
					</div>
					<div class="req_pass">
						<a class="btn-more btn-register" href="<?php echo $this->url->get('dang-ky') ?>" title="Đăng ký">Đăng ký</a>
					</div>
				</form>
			</div>
			<div id="recover-password" style="display:none;" class="userbox">
				<div class="accounttype">
					<h2>Phục hồi mật khẩu</h2>
				</div>		
				<form accept-charset='UTF-8' action='' method='post'>
					<input name='form_type' type='hidden' value='recover_customer_password'>
					<input name='utf8' type='hidden' value='✓'>
					<div class="clearfix large_form">
						<input type="email" value="" size="30" name="email" placeholder="Email" id="recover-email" class="text" />
					</div>
					<div class="action_bottom">
						<input class="btn-more btn-login" type="submit" value="Gửi" />
					</div>
					<div class="req_pass">
						<a class="btn-more btn-register" href="#" onclick="hideRecoverPasswordForm();return false;">Hủy</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function showRecoverPasswordForm() {
	document.getElementById('recover-password').style.display = 'block';
	document.getElementById('login').style.display='none';
	}

	function hideRecoverPasswordForm() {
	document.getElementById('recover-password').style.display = 'none';
	document.getElementById('login').style.display = 'block';
	}

	if (window.location.hash == '#recover') { showRecoverPasswordForm() }
</script>